#ifndef __CONSTANTS_HPP_
#define __CONSTANTS_HPP_
#define SERVER_ADDR "localhost"
#define SERVER_PORT 4000
#define MESSAGE_LEN 256
#define PACKET_LEN 500
#define TIME_SEND_AGAIN 5000
#define TIMEOUT_ON 1
#define TIMEOUT_OFF 0

#define FIRST_PORT 4001
#define LAST_PORT 6000

#define MAX_DEVICES 2

enum TYPES
{
  TYPE_DATA,
  TYPE_ACK,
  TYPE_MAKE_CONNECTION,
  TYPE_SEND_FILE
};

#endif